apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: task-queue
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: api
  type: ClusterIP